"""empty message

Revision ID: 3e5d2fcabda6
Revises: 462a4b715f81
Create Date: 2023-03-27 14:16:41.615560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5d2fcabda6'
down_revision = '462a4b715f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=140),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=140),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
